name: Cleanup GHCR

on:
  # 毎日午前3時 (UTC) に実行
  schedule:
    - cron: "0 3 * * *"
  # 手動実行も可能にする
  workflow_dispatch:

jobs:
  delete-untagged-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          # あなたのリポジトリ名（オーナー名を含む）
          package-name: 'streamlit_sample_app'
          # パッケージの種類を指定 (必須)
          package-type: 'container'
          # タグの有無に関わらず、最新の5バージョンを常に保持する
          min-versions-to-keep: 5
          # このオプションを削除することで、タグ付き・タグなし両方の古いバージョンが削除対象になります
          # delete-untagged-versions: true